Controllers/AdminController.cs
using System.Diagnostics;
using System.Security.Claims;
using MicroFIN.Core;
using MicroFIN.Core.Contracts;
using MicroFIN.Core.Services;
using Microsoft.AspNetCore.Mvc;
using MicroFIN.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace MicroFIN.Controllers;

[Authorize]
public class AdminController : Controller
{
    private readonly ILogger<AdminController> _logger;
    private readonly IMicroFinDbContext _context;
    private readonly IReportRepo _repoReport;
    

    public AdminController(ILogger<AdminController> logger,IMicroFinDbContext context, IReportRepo repoReport)
    {
        _logger = logger;
        _context = context;
        _repoReport = repoReport;
    }

   
    [Authorize(Roles ="sysadmin,admin, user")]
    public IActionResult Index()
    {
        return View();
    }

    [Authorize(Roles ="sysadmin,admin")]
    public IActionResult Setting()
    {
        return View();

    }
    public IActionResult Customers()
    {
        return View();
    }
    public IActionResult Agents()
    {
        return View();
    }
    public IActionResult Investors()
    {
        return View();
    }
    public IActionResult Expences()
    {
        return View();
    }
    
    public IActionResult Diary()
    {
        return View();
    }
    
    [HttpGet("admin/diarydetail/{number}")]
    public async Task<IActionResult> DiaryDetail(int number)
    {
        var _res = new DiaryResponseViewModel();
        var diary = 
            await _context.Dairies
                .Include("Customer")
                .Include("DiaryInstallments")
                .Include("Agent")
                .FirstOrDefaultAsync(x=>x.DiaryNumber==number && x.IsActive==true);

        _res.Id = diary.Id;
        _res.Installment = diary.Installment;
        _res.AgentId = diary.AgentId;
        _res.CustomerId = diary.CustomerId;
        _res.CustomerMobile = diary.Customer.Mobile;
        _res.CustomerName = diary.Customer.AccountName;
        _res.CustomerFatherName = diary.Customer.FatherName;
        _res.CustomerBusiness = diary.Customer.BusinessName;
        _res.CustomerAddress = diary.Customer.Address;
        _res.CustomerRemarks = diary.Customer.Remarks;
        _res.DiaryNumber = diary.DiaryNumber;
        _res.EndDate = diary.EndDate;
        _res.HasAgent = diary.HasAgent;
        _res.IsCompleted = diary.IsCompleted;
        _res.LoanAmount = diary.LoanAmount;
        _res.StartDate = diary.StartDate;
        _res.TotalAmount = diary.RecoveryAmount;
        _res.TotalBalanceAmount = diary.TotalBalanceAmount;

        _res.Installments = new List<DiaryInstallmentResponseViewModel>();

        double _lastDue = 0;
        double _todayBalance = 0;
        _res.TodayBalance = 0;
        foreach (var item in diary.DiaryInstallments)
        {
            _todayBalance = _todayBalance + item.BalanceAmount;

            if (DateTime.Parse(item.InstallmentDate.ToString("yyyy-MM-dd")) <= DateTime.Parse(DateTime.Now.ToString("yyyy-MM-dd")))
            {
                _res.TodayBalance = _todayBalance;
            }
            
            _res.Installments.Add(new DiaryInstallmentResponseViewModel
            {
                Id = item.Id,
                BalanceAmount = item.BalanceAmount,
                InstallmentAmount = item.InstallmentAmount,
                InstallmentDate = item.InstallmentDate,
                InstallmentNumber = item.InstallmentNumber,
                PaidAmount = item.PaidAmount
            });
            //_lastDue = (_lastDue + item.BalanceAmount);
        }
        
        
        
        
        var fromDairies = 
            await _context.Transactions
                .Include("Investor")
                .Where(x=>x.DiaryId==diary.AccountId && x.TransactionType==TransactionType.Transfer)
                .ToListAsync();
        
        var toDairies = 
            await _context.Transactions
                .Where(x=>x.FromDiaryId==diary.AccountId)
                .ToListAsync();
        _res.FromDairies = new();
        var accountName = "";
        foreach (var item in fromDairies)
        {
            if (item.FromDiaryId > 0)
            {
                accountName = _context.Accounts.FirstOrDefault(x => x.Id == item.FromDiaryId)?.AccountName;
            }
            _res.FromDairies.Add(new DiaryReffViewModel()
            {
                Invester = "",
                AccountName = (item.InvestorId>0?item.Investor.AccountName:accountName),
                TransferAmount = Math.Abs(item.Amount),
                TransferDate = item.CreatedOn??DateTime.Now
            });
        }

        _res.ToDairies = new();
        foreach (var item in toDairies)
        {
            if (item.FromDiaryId > 0)
            {
                accountName = _context.Accounts.FirstOrDefault(x => x.Id == item.DiaryId)?.AccountName;
            }
            _res.ToDairies.Add(new DiaryReffViewModel()
            {
                Invester = "",
                AccountName = accountName,
                TransferAmount =Math.Abs(item.Amount),
                TransferDate = item.CreatedOn??DateTime.Now
            });
        }        
        return PartialView("_DiaryDetailPartial",_res);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
    
    
    
    [HttpGet("admin/dashboard/counter")]
    public async Task<ResponseObject<DashboardCounterViewModel>> GetCounter()
    {

        var _diariesCount = await _context.Dairies.CountAsync(x => x.IsActive == true);
        var _customersCount = await _context.Accounts.CountAsync(x => x.IsActive == true && x.AccountType==AccountType.Customer && x.IsDefault==false);
        var _totalRevenue = await _context.Dairies.Where(x => x.IsActive == true).SumAsync(f=>f.RecoveryAmount-f.TotalBalanceAmount);
        var _totalExpenses = await _context.Expenses.Where(x => x.IsActive == true).SumAsync(f=>f.Amount);

        var ct = await _repoReport.GetAllLedgerCounter();

        return new ResponseObject<DashboardCounterViewModel>(new DashboardCounterViewModel
        {
            Customers = _customersCount,
            Diaries = _diariesCount,
            RevenueTotal = Convert.ToInt32(_totalRevenue),
            ExpensesTotal = Convert.ToInt32(_totalExpenses),
            TotalCredit = ct.TotalCredit,
            TotalDebit = ct.TotalDebit,
            TotalBalance = ct.TotalBalance
        });
    }
    
}

Controllers/ReportController.cs
using System.Diagnostics;
using System.Security.Claims;
using MicroFIN.Core;
using MicroFIN.Core.Services;
using Microsoft.AspNetCore.Mvc;
using MicroFIN.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace MicroFIN.Controllers;
[Authorize]
public class ReportController : Controller
{
    private readonly ILogger<ReportController> _logger;
    private readonly IMicroFinDbContext _context;
    private readonly IReportRepo reportRepo;

    public ReportController(ILogger<ReportController> logger, IMicroFinDbContext context, IReportRepo reportRepo)
    {
        _logger = logger;
        _context = context;
        this.reportRepo = reportRepo;
    }

    [Authorize(Roles = "sysadmin,admin, user")]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet("report/getIncomeExpensesReport")]
    public async Task<ResponseObject<IEnumerable<IncomeExpensesReportModel>?>> GetIncomeExpensesReport(int id)
    {
        List<IncomeExpensesReportModel> _lstrepData = new List<IncomeExpensesReportModel>();

        var _DiaryColl = await _context.DiaryInstallments.Select(x => x.PaidAmount).SumAsync();
        _lstrepData.Add(new IncomeExpensesReportModel { IsIncome = true, Category = "Diary Collection", Amount = decimal.Parse(_DiaryColl.ToString()) });

        var _aList = (from d in _context.Expenses
                      select new { d.Category, d.Amount } into x
                      group x by new { x.Category } into g
                      select new
                      {
                          Category = g.Key.Category,
                          Amount = g.Select(x => x.Amount).Sum()
                      });
        foreach (var item in _aList)
        {
            _lstrepData.Add(new IncomeExpensesReportModel { IsIncome = false, Category = item.Category, Amount = decimal.Parse(item.Amount.ToString()) });
        }

        return new ResponseObject<IEnumerable<IncomeExpensesReportModel>>(_lstrepData);
    }


    [HttpGet("/report/customers")]
    public async Task<IActionResult> GetCustomerWithFilter()
    {
        List<ReportCustomerViewModel> _lstrepData = await  (from c in _context.Accounts
                                                     join d in _context.Dairies on c.Id equals d.CustomerId
                                                     where c.AccountType == Core.Contracts.AccountType.Customer
                                                     orderby c.AccountName
                                                     select new ReportCustomerViewModel
                                                     {
                                                         CustomerId = c.Id,
                                                         CustomerName = c.AccountName,
                                                         FatherName = c.FatherName,
                                                         DiaryId = d.Id,
                                                         DiaryNumber = d.DiaryNumber,
                                                         LoanAmount = d.LoanAmount,
                                                         RecoveryAmount = d.RecoveryAmount,
                                                         PaidAmount = d.TotalPaidAmount,
                                                         BalanceAmount = d.TotalBalanceAmount,
                                                         IsCompleted = d.IsCompleted

                                                     }).ToListAsync();


        return PartialView("_CustomersPartial", _lstrepData);
    }
    
    [HttpGet("/report/ledgers")]
    public async Task<IActionResult> GetLedgersWithFilter()
    {
        var _lst = await reportRepo.GetAllLedgers();
        return PartialView("_LedgerReportPartial",_lst);
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MicroFIN</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/simple-datatables/style.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.4.0/css/responsive.bootstrap5.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.2/css/buttons.bootstrap5.min.css"/>

    
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>

    @* <link rel="stylesheet" href="~/MicroFIN.styles.css" asp-append-version="true"/> *@
</head>
<body>
<partial name="_CookieConsentPartial"/>
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="/" class="logo d-flex align-items-center">
        <img src="/images/logo.png" alt="">
        <span class="d-none d-lg-block"><small>JAI BHOLE FINANCE</small></span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="number" id="txtsearchDiarynumber" value="" placeholder="Enter Diary Number"  title="Enter Diary Number">
        <button type="button" title="Search" onclick="onClickSearch(this)"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">
        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->
          <li class="nav-item pe-3">
              <a class="nav-link nav-profile d-flex align-items-center pe-0" asp-action="Setting" asp-controller="Admin">
                  <span class="d-md-block ps-2">@User.Identity.Name</span>
              </a>
          </li>
          <li class="nav-item dropdown pe-3">
             
              <a class="nav-link nav-profile d-flex align-items-center pe-0" asp-action="logout" asp-controller="account">
                  <i class="bi bi-box-arrow-right" style="font-size: 1.5rem;"></i>
              </a>
              @* <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown"> *@
              @*   <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle"> *@
              @*   <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span> *@
              @* </a><!-- End Profile Iamge Icon --> *@
          </li><!-- End Profile Nav -->
      </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">
  <ul class="sidebar-nav" id="sidebar-nav">
      <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index"><i class="bi bi-grid"></i><span>Dashboard</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link collapsed" asp-area="" asp-controller="Admin" asp-action="Investors"><i class="bi bi-person-badge-fill"></i><span>Investors</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link collapsed" asp-area="" asp-controller="Admin" asp-action="Agents"><i class="bi bi-person-badge-fill"></i><span>Agents</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link collapsed" asp-area="" asp-controller="Admin" asp-action="Customers"><i class="bi bi-people"></i><span>Customers</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link collapsed" asp-area="" asp-controller="Admin" asp-action="Diary"><i class="bi bi-book"></i><span>Dairies</span></a>
      </li>
     
      <li class="nav-item">
          <a class="nav-link collapsed" asp-area="" asp-controller="Admin" asp-action="Expences"><i class="bi bi-currency-rupee"></i><span>Expences</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link collapsed" asp-area="" asp-controller="Report" asp-action="Index"><i class="bi bi-stack"></i><span>Reports</span></a>
      </li>
  </ul>

  </aside><!-- End Sidebar-->
<main id="main" class="main">
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

</main>
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>JAI BHOLE FINANCE</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
     <small> Designed by <a href="https://kodonic.com/">Kodonic Digitech Private Limited</a></small>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<div class="loaderbody" id="loaderbody">
    <div class="loader"></div>
</div>
@* <div class="modal" tabindex="-1" role="dialog" id="form-modal"> *@
@*     <div class="modal-dialog" role="document"> *@
@*         <div class="modal-content"> *@
@*             <div class="modal-header"> *@
@*                 <h5 class="modal-title"></h5> *@
@*                 <button type="button" class="close" data-dismiss="modal" aria-label="Close"> *@
@*                     <span aria-hidden="true">×</span> *@
@*                 </button> *@
@*             </div> *@
@*             <div class="modal-body"> *@
@*             </div> *@
@*         </div> *@
@*     </div> *@
@* </div> *@

<!-- Diary Detail Modal -->
<div class="modal fade" id="detailDiaryModel" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header py-2">
        <h5 class="modal-title" id="staticBackdropLabel">Diary Detail</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="divDiaryDetail"></div>
    </div>
  </div>
</div>





<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/simple-datatables/simple-datatables.js" rel="stylesheet"></script>
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.4.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.bootstrap5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.colVis.min.js"></script>
<script src="~/js/moment.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/lib/printThis/printThis.js"></script>
<script src="~/js/main.js" asp-append-version="true"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>